[profile.default]
src = "src/foundry-contracts"
out = "out"
libs = [
    "lib",
    "node_modules",
]
remappings = [
    "@benchmarking-cross-chain-bridges/=src/contracts",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
